# Generated by Django 5.2.1 on 2025-06-09 21:24

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.polygon
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpolygon",
            options={
                "verbose_name": "User Polygon",
                "verbose_name_plural": "User Polygons",
            },
        ),
        migrations.RemoveField(
            model_name="userpolygon",
            name="geom",
        ),
        migrations.AddField(
            model_name="userpolygon",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=django.contrib.gis.geos.polygon.Polygon(
                    ((0, 0), (0, 0.0001), (0.0001, 0.0001), (0.0001, 0), (0, 0))
                ),
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="userpolygon",
            name="crop_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
